#include "../qjs_wrapper.hpp"
#include <raylib.h>
#include "rl_module.hpp"

namespace RaylibModule {

    void register_raylib_objects(const qjs::Engine &engine, qjs::Module &module) {

        auto palette_obj = engine.make_object()
             .set_constant("LIGHTGRAY", LIGHTGRAY)
             .set_constant("GRAY", GRAY)
             .set_constant("DARKGRAY", DARKGRAY)
             .set_constant("YELLOW", YELLOW)
             .set_constant("GOLD", GOLD)
             .set_constant("ORANGE", ORANGE)
             .set_constant("PINK", PINK)
             .set_constant("RED", RED)
             .set_constant("MAROON", MAROON)
             .set_constant("GREEN", GREEN)
             .set_constant("LIME", LIME)
             .set_constant("DARKGREEN", DARKGREEN)
             .set_constant("SKYBLUE", SKYBLUE)
             .set_constant("BLUE", BLUE)
             .set_constant("DARKBLUE", DARKBLUE)
             .set_constant("PURPLE", PURPLE)
             .set_constant("VIOLET", VIOLET)
             .set_constant("DARKPURPLE", DARKPURPLE)
             .set_constant("BEIGE", BEIGE)
             .set_constant("BROWN", BROWN)
             .set_constant("DARKBROWN", DARKBROWN)
             .set_constant("WHITE", WHITE)
             .set_constant("BLACK", BLACK)
             .set_constant("BLANK", BLANK)
             .set_constant("MAGENTA", MAGENTA)
             .set_constant("RAYWHITE", RAYWHITE);
        module.add("Palette", palette_obj);

        auto info_obj = engine.make_object()
            .set_constant("Version", RAYLIB_VERSION)
            .set_constant("VersionMajor", RAYLIB_VERSION_MAJOR)
            .set_constant("VersionMinor", RAYLIB_VERSION_MINOR)
            .set_constant("VersionPatch", RAYLIB_VERSION_PATCH)
            .set_constant("Website", "https://www.raylib.com");
        module.add("Info", info_obj);

        // Enum: ConfigFlags
        auto ConfigFlags_obj = engine.make_object()
            .set_constant("FLAG_VSYNC_HINT", FLAG_VSYNC_HINT)
            .set_constant("FLAG_FULLSCREEN_MODE", FLAG_FULLSCREEN_MODE)
            .set_constant("FLAG_WINDOW_RESIZABLE", FLAG_WINDOW_RESIZABLE)
            .set_constant("FLAG_WINDOW_UNDECORATED", FLAG_WINDOW_UNDECORATED)
            .set_constant("FLAG_WINDOW_HIDDEN", FLAG_WINDOW_HIDDEN)
            .set_constant("FLAG_WINDOW_MINIMIZED", FLAG_WINDOW_MINIMIZED)
            .set_constant("FLAG_WINDOW_MAXIMIZED", FLAG_WINDOW_MAXIMIZED)
            .set_constant("FLAG_WINDOW_UNFOCUSED", FLAG_WINDOW_UNFOCUSED)
            .set_constant("FLAG_WINDOW_TOPMOST", FLAG_WINDOW_TOPMOST)
            .set_constant("FLAG_WINDOW_ALWAYS_RUN", FLAG_WINDOW_ALWAYS_RUN)
            .set_constant("FLAG_WINDOW_TRANSPARENT", FLAG_WINDOW_TRANSPARENT)
            .set_constant("FLAG_WINDOW_HIGHDPI", FLAG_WINDOW_HIGHDPI)
            .set_constant("FLAG_WINDOW_MOUSE_PASSTHROUGH", FLAG_WINDOW_MOUSE_PASSTHROUGH)
            .set_constant("FLAG_BORDERLESS_WINDOWED_MODE", FLAG_BORDERLESS_WINDOWED_MODE)
            .set_constant("FLAG_MSAA_4X_HINT", FLAG_MSAA_4X_HINT)
            .set_constant("FLAG_INTERLACED_HINT", FLAG_INTERLACED_HINT);
        module.add("ConfigFlags", ConfigFlags_obj);

        // Enum: KeyboardKey
        auto KeyboardKey_obj = engine.make_object()
            .set_constant("KEY_NULL", KEY_NULL)
            .set_constant("KEY_APOSTROPHE", KEY_APOSTROPHE)
            .set_constant("KEY_COMMA", KEY_COMMA)
            .set_constant("KEY_MINUS", KEY_MINUS)
            .set_constant("KEY_PERIOD", KEY_PERIOD)
            .set_constant("KEY_SLASH", KEY_SLASH)
            .set_constant("KEY_ZERO", KEY_ZERO)
            .set_constant("KEY_ONE", KEY_ONE)
            .set_constant("KEY_TWO", KEY_TWO)
            .set_constant("KEY_THREE", KEY_THREE)
            .set_constant("KEY_FOUR", KEY_FOUR)
            .set_constant("KEY_FIVE", KEY_FIVE)
            .set_constant("KEY_SIX", KEY_SIX)
            .set_constant("KEY_SEVEN", KEY_SEVEN)
            .set_constant("KEY_EIGHT", KEY_EIGHT)
            .set_constant("KEY_NINE", KEY_NINE)
            .set_constant("KEY_SEMICOLON", KEY_SEMICOLON)
            .set_constant("KEY_EQUAL", KEY_EQUAL)
            .set_constant("KEY_A", KEY_A)
            .set_constant("KEY_B", KEY_B)
            .set_constant("KEY_C", KEY_C)
            .set_constant("KEY_D", KEY_D)
            .set_constant("KEY_E", KEY_E)
            .set_constant("KEY_F", KEY_F)
            .set_constant("KEY_G", KEY_G)
            .set_constant("KEY_H", KEY_H)
            .set_constant("KEY_I", KEY_I)
            .set_constant("KEY_J", KEY_J)
            .set_constant("KEY_K", KEY_K)
            .set_constant("KEY_L", KEY_L)
            .set_constant("KEY_M", KEY_M)
            .set_constant("KEY_N", KEY_N)
            .set_constant("KEY_O", KEY_O)
            .set_constant("KEY_P", KEY_P)
            .set_constant("KEY_Q", KEY_Q)
            .set_constant("KEY_R", KEY_R)
            .set_constant("KEY_S", KEY_S)
            .set_constant("KEY_T", KEY_T)
            .set_constant("KEY_U", KEY_U)
            .set_constant("KEY_V", KEY_V)
            .set_constant("KEY_W", KEY_W)
            .set_constant("KEY_X", KEY_X)
            .set_constant("KEY_Y", KEY_Y)
            .set_constant("KEY_Z", KEY_Z)
            .set_constant("KEY_LEFT_BRACKET", KEY_LEFT_BRACKET)
            .set_constant("KEY_BACKSLASH", KEY_BACKSLASH)
            .set_constant("KEY_RIGHT_BRACKET", KEY_RIGHT_BRACKET)
            .set_constant("KEY_GRAVE", KEY_GRAVE)
            .set_constant("KEY_SPACE", KEY_SPACE)
            .set_constant("KEY_ESCAPE", KEY_ESCAPE)
            .set_constant("KEY_ENTER", KEY_ENTER)
            .set_constant("KEY_TAB", KEY_TAB)
            .set_constant("KEY_BACKSPACE", KEY_BACKSPACE)
            .set_constant("KEY_INSERT", KEY_INSERT)
            .set_constant("KEY_DELETE", KEY_DELETE)
            .set_constant("KEY_RIGHT", KEY_RIGHT)
            .set_constant("KEY_LEFT", KEY_LEFT)
            .set_constant("KEY_DOWN", KEY_DOWN)
            .set_constant("KEY_UP", KEY_UP)
            .set_constant("KEY_PAGE_UP", KEY_PAGE_UP)
            .set_constant("KEY_PAGE_DOWN", KEY_PAGE_DOWN)
            .set_constant("KEY_HOME", KEY_HOME)
            .set_constant("KEY_END", KEY_END)
            .set_constant("KEY_CAPS_LOCK", KEY_CAPS_LOCK)
            .set_constant("KEY_SCROLL_LOCK", KEY_SCROLL_LOCK)
            .set_constant("KEY_NUM_LOCK", KEY_NUM_LOCK)
            .set_constant("KEY_PRINT_SCREEN", KEY_PRINT_SCREEN)
            .set_constant("KEY_PAUSE", KEY_PAUSE)
            .set_constant("KEY_F1", KEY_F1)
            .set_constant("KEY_F2", KEY_F2)
            .set_constant("KEY_F3", KEY_F3)
            .set_constant("KEY_F4", KEY_F4)
            .set_constant("KEY_F5", KEY_F5)
            .set_constant("KEY_F6", KEY_F6)
            .set_constant("KEY_F7", KEY_F7)
            .set_constant("KEY_F8", KEY_F8)
            .set_constant("KEY_F9", KEY_F9)
            .set_constant("KEY_F10", KEY_F10)
            .set_constant("KEY_F11", KEY_F11)
            .set_constant("KEY_F12", KEY_F12)
            .set_constant("KEY_LEFT_SHIFT", KEY_LEFT_SHIFT)
            .set_constant("KEY_LEFT_CONTROL", KEY_LEFT_CONTROL)
            .set_constant("KEY_LEFT_ALT", KEY_LEFT_ALT)
            .set_constant("KEY_LEFT_SUPER", KEY_LEFT_SUPER)
            .set_constant("KEY_RIGHT_SHIFT", KEY_RIGHT_SHIFT)
            .set_constant("KEY_RIGHT_CONTROL", KEY_RIGHT_CONTROL)
            .set_constant("KEY_RIGHT_ALT", KEY_RIGHT_ALT)
            .set_constant("KEY_RIGHT_SUPER", KEY_RIGHT_SUPER)
            .set_constant("KEY_KB_MENU", KEY_KB_MENU)
            .set_constant("KEY_KP_0", KEY_KP_0)
            .set_constant("KEY_KP_1", KEY_KP_1)
            .set_constant("KEY_KP_2", KEY_KP_2)
            .set_constant("KEY_KP_3", KEY_KP_3)
            .set_constant("KEY_KP_4", KEY_KP_4)
            .set_constant("KEY_KP_5", KEY_KP_5)
            .set_constant("KEY_KP_6", KEY_KP_6)
            .set_constant("KEY_KP_7", KEY_KP_7)
            .set_constant("KEY_KP_8", KEY_KP_8)
            .set_constant("KEY_KP_9", KEY_KP_9)
            .set_constant("KEY_KP_DECIMAL", KEY_KP_DECIMAL)
            .set_constant("KEY_KP_DIVIDE", KEY_KP_DIVIDE)
            .set_constant("KEY_KP_MULTIPLY", KEY_KP_MULTIPLY)
            .set_constant("KEY_KP_SUBTRACT", KEY_KP_SUBTRACT)
            .set_constant("KEY_KP_ADD", KEY_KP_ADD)
            .set_constant("KEY_KP_ENTER", KEY_KP_ENTER)
            .set_constant("KEY_KP_EQUAL", KEY_KP_EQUAL)
            .set_constant("KEY_BACK", KEY_BACK)
            .set_constant("KEY_MENU", KEY_MENU)
            .set_constant("KEY_VOLUME_UP", KEY_VOLUME_UP)
            .set_constant("KEY_VOLUME_DOWN", KEY_VOLUME_DOWN);
        module.add("KeyboardKey", KeyboardKey_obj);

        // Enum: MouseButton
        auto MouseButton_obj = engine.make_object()
            .set_constant("MOUSE_BUTTON_LEFT", MOUSE_BUTTON_LEFT)
            .set_constant("MOUSE_BUTTON_RIGHT", MOUSE_BUTTON_RIGHT)
            .set_constant("MOUSE_BUTTON_MIDDLE", MOUSE_BUTTON_MIDDLE)
            .set_constant("MOUSE_BUTTON_SIDE", MOUSE_BUTTON_SIDE)
            .set_constant("MOUSE_BUTTON_EXTRA", MOUSE_BUTTON_EXTRA)
            .set_constant("MOUSE_BUTTON_FORWARD", MOUSE_BUTTON_FORWARD)
            .set_constant("MOUSE_BUTTON_BACK", MOUSE_BUTTON_BACK);
        module.add("MouseButton", MouseButton_obj);

        // Enum: MouseCursor
        auto MouseCursor_obj = engine.make_object()
            .set_constant("MOUSE_CURSOR_DEFAULT", MOUSE_CURSOR_DEFAULT)
            .set_constant("MOUSE_CURSOR_ARROW", MOUSE_CURSOR_ARROW)
            .set_constant("MOUSE_CURSOR_IBEAM", MOUSE_CURSOR_IBEAM)
            .set_constant("MOUSE_CURSOR_CROSSHAIR", MOUSE_CURSOR_CROSSHAIR)
            .set_constant("MOUSE_CURSOR_POINTING_HAND", MOUSE_CURSOR_POINTING_HAND)
            .set_constant("MOUSE_CURSOR_RESIZE_EW", MOUSE_CURSOR_RESIZE_EW)
            .set_constant("MOUSE_CURSOR_RESIZE_NS", MOUSE_CURSOR_RESIZE_NS)
            .set_constant("MOUSE_CURSOR_RESIZE_NWSE", MOUSE_CURSOR_RESIZE_NWSE)
            .set_constant("MOUSE_CURSOR_RESIZE_NESW", MOUSE_CURSOR_RESIZE_NESW)
            .set_constant("MOUSE_CURSOR_RESIZE_ALL", MOUSE_CURSOR_RESIZE_ALL)
            .set_constant("MOUSE_CURSOR_NOT_ALLOWED", MOUSE_CURSOR_NOT_ALLOWED);
        module.add("MouseCursor", MouseCursor_obj);

        // Enum: GamepadButton
        auto GamepadButton_obj = engine.make_object()
            .set_constant("GAMEPAD_BUTTON_UNKNOWN", GAMEPAD_BUTTON_UNKNOWN)
            .set_constant("GAMEPAD_BUTTON_LEFT_FACE_UP", GAMEPAD_BUTTON_LEFT_FACE_UP)
            .set_constant("GAMEPAD_BUTTON_LEFT_FACE_RIGHT", GAMEPAD_BUTTON_LEFT_FACE_RIGHT)
            .set_constant("GAMEPAD_BUTTON_LEFT_FACE_DOWN", GAMEPAD_BUTTON_LEFT_FACE_DOWN)
            .set_constant("GAMEPAD_BUTTON_LEFT_FACE_LEFT", GAMEPAD_BUTTON_LEFT_FACE_LEFT)
            .set_constant("GAMEPAD_BUTTON_RIGHT_FACE_UP", GAMEPAD_BUTTON_RIGHT_FACE_UP)
            .set_constant("GAMEPAD_BUTTON_RIGHT_FACE_RIGHT", GAMEPAD_BUTTON_RIGHT_FACE_RIGHT)
            .set_constant("GAMEPAD_BUTTON_RIGHT_FACE_DOWN", GAMEPAD_BUTTON_RIGHT_FACE_DOWN)
            .set_constant("GAMEPAD_BUTTON_RIGHT_FACE_LEFT", GAMEPAD_BUTTON_RIGHT_FACE_LEFT)
            .set_constant("GAMEPAD_BUTTON_LEFT_TRIGGER_1", GAMEPAD_BUTTON_LEFT_TRIGGER_1)
            .set_constant("GAMEPAD_BUTTON_LEFT_TRIGGER_2", GAMEPAD_BUTTON_LEFT_TRIGGER_2)
            .set_constant("GAMEPAD_BUTTON_RIGHT_TRIGGER_1", GAMEPAD_BUTTON_RIGHT_TRIGGER_1)
            .set_constant("GAMEPAD_BUTTON_RIGHT_TRIGGER_2", GAMEPAD_BUTTON_RIGHT_TRIGGER_2)
            .set_constant("GAMEPAD_BUTTON_MIDDLE_LEFT", GAMEPAD_BUTTON_MIDDLE_LEFT)
            .set_constant("GAMEPAD_BUTTON_MIDDLE", GAMEPAD_BUTTON_MIDDLE)
            .set_constant("GAMEPAD_BUTTON_MIDDLE_RIGHT", GAMEPAD_BUTTON_MIDDLE_RIGHT)
            .set_constant("GAMEPAD_BUTTON_LEFT_THUMB", GAMEPAD_BUTTON_LEFT_THUMB)
            .set_constant("GAMEPAD_BUTTON_RIGHT_THUMB", GAMEPAD_BUTTON_RIGHT_THUMB);
        module.add("GamepadButton", GamepadButton_obj);

        // Enum: GamepadAxis
        auto GamepadAxis_obj = engine.make_object()
            .set_constant("GAMEPAD_AXIS_LEFT_X", GAMEPAD_AXIS_LEFT_X)
            .set_constant("GAMEPAD_AXIS_LEFT_Y", GAMEPAD_AXIS_LEFT_Y)
            .set_constant("GAMEPAD_AXIS_RIGHT_X", GAMEPAD_AXIS_RIGHT_X)
            .set_constant("GAMEPAD_AXIS_RIGHT_Y", GAMEPAD_AXIS_RIGHT_Y)
            .set_constant("GAMEPAD_AXIS_LEFT_TRIGGER", GAMEPAD_AXIS_LEFT_TRIGGER)
            .set_constant("GAMEPAD_AXIS_RIGHT_TRIGGER", GAMEPAD_AXIS_RIGHT_TRIGGER);
        module.add("GamepadAxis", GamepadAxis_obj);

        // Enum: CameraMode
        auto CameraMode_obj = engine.make_object()
            .set_constant("CAMERA_CUSTOM", CAMERA_CUSTOM)
            .set_constant("CAMERA_FREE", CAMERA_FREE)
            .set_constant("CAMERA_ORBITAL", CAMERA_ORBITAL)
            .set_constant("CAMERA_FIRST_PERSON", CAMERA_FIRST_PERSON)
            .set_constant("CAMERA_THIRD_PERSON", CAMERA_THIRD_PERSON);
        module.add("CameraMode", CameraMode_obj);

        // Enum: CameraProjection
        auto CameraProjection_obj = engine.make_object()
            .set_constant("CAMERA_PERSPECTIVE", CAMERA_PERSPECTIVE)
            .set_constant("CAMERA_ORTHOGRAPHIC", CAMERA_ORTHOGRAPHIC);
        module.add("CameraProjection", CameraProjection_obj);

    }

}