name: Verify Build
concurrency:
  group: verify-build
  cancel-in-progress: false
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          actions-cache-key: ${{ runner.os }}-xmake-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake -y
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          actions-cache-key: ${{ runner.os }}-xmake-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake f -p linux -a x86_64 --sdk=/usr/bin --cc=gcc-14 --cxx=g++-14 -y && xmake -y
  mac-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          actions-cache-key: ${{ runner.os }}-xmake-${{ hashFiles('xmake.lua') }}
      - name: Build
        run: xmake -y